// Random utility helper generated by AI assistanttttt
function getRandomNumber(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

console.log("Random number generated: ", getRandomNumber(1, 100));
